name: ClearMobPlugin
version: 1.0
main: com.clearmob.clearmob.ClearMobPlugin
api-version: 1.20
description: A plugin to kill mobs with warnings.
commands:
  clearmob:
    description: Manage the ClearMobPlugin
    usage: /<command> <subcommand>
    permission: clearmob.admin
    permission-message: You do not have permission to use this command.
    aliases: [cm]
